repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--settings-path=pyproject.toml"]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      args: ["--config=pyproject.toml"]

- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      additional_dependencies: [pylint]
      types: [python]
      args: [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--rcfile=.pylintrc", # Link to your config file
        "--recursive=y",
        "--fail-under=5",
        # "--disable=all"
      ]

- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: python
      pass_filenames: false
      always_run: true
      additional_dependencies: [pytest]
