version: '3.8'

services:
  model_service:
    container_name: model-service
    image: model-service
    build:
      context: ./NewsBuddy/model_service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./NewsBuddy/model_service/.env

  frontend:
    container_name: user-frontend
    image: user-frontend
    build:
      context: ./NewsBuddy/user_frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8501:8501
    env_file:
      - ./NewsBuddy/model_service/.env

  # Disabled for now
  # prometheus:
  #   container_name: prometheus
  #   image: prometheus-newsbuddy
  #   build:
  #     context: ./infrastructure/prometheus/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9090:9090