version: '3'

services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    env_file:
      - .env
    volumes:
       - db:/var/lib/postgresql/data
    networks:
      - inner
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DB_USER}"]
    secrets:
       - db_password

  app:
    build: .
    environment:
       POSTGRES_HOST: ${DB_HOST}:${DB_PORT}
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - inner
      - common
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    secrets:
       - db_password

networks:
  inner:
  common:
    # name: network for communication with other services
    external: true

volumes:
    db:

secrets:
   db_password:
     file: db_password.txt
